basket/urls.py
from django.urls import path

from . import views

app_name = 'basket'

urlpatterns = [
    path('', views.basket_summary, name='basket_summary'),
    path('add/', views.basket_add, name='basket_add'),
    path('delete/', views.basket_delete, name='basket_delete'),
    path('update/', views.basket_update, name='basket_update'),
]

checkout/urls.py
from django.urls import path

from . import views

app_name = "checkout"

urlpatterns = [
    path("deliverychoices/", views.deliverychoices, name="deliverychoices"),
    path("basket_update_delivery/", views.basket_update_delivery, name="basket_update_delivery"),
    path("delivery_address/", views.delivery_address, name="delivery_address"),
    path("payment_selection/", views.payment_selection, name="payment_selection"),
    path("payment_complete/", views.payment_complete, name="payment_complete"),
    path("payment_successful/", views.payment_successful, name="payment_successful"),
]

ecommerce/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    path("checkout/", include("checkout.urls", namespace="checkout")),
    path("basket/", include("basket.urls", namespace="basket")),
    path("account/", include("account.urls", namespace="account")),
    path("orders/", include("orders.urls", namespace="orders")),
]
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path

from . import views

app_name = 'store'

urlpatterns = [
    path('', views.product_all, name='store_home'),
    path('<slug:slug>', views.product_detail, name='product_detail'),
    path('shop/<slug:category_slug>/', views.category_list, name='category_list'),
]

basket/views.py
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, render

from store.models import Product

from .basket import Basket


def basket_summary(request):
    basket = Basket(request)
    return render(request, 'basket/summary.html', {'basket': basket})


def basket_add(request):
    basket = Basket(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid'))
        product_qty = int(request.POST.get('productqty'))
        product = get_object_or_404(Product, id=product_id)
        basket.add(product=product, qty=product_qty)

        basketqty = basket.__len__()
        response = JsonResponse({'qty': basketqty})
        return response


def basket_delete(request):
    basket = Basket(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid'))
        basket.delete(product=product_id)

        basketqty = basket.__len__()
        baskettotal = basket.get_total_price()
        response = JsonResponse({'qty': basketqty, 'subtotal': baskettotal})
        return response


def basket_update(request):
    basket = Basket(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid'))
        product_qty = int(request.POST.get('productqty'))
        basket.update(product=product_id, qty=product_qty)

        basketqty = basket.__len__()
        basketsubtotal = basket.get_subtotal_price()
        response = JsonResponse({'qty': basketqty, 'subtotal': basketsubtotal})
        return response

templates/basket/summary.html
{% extends "../base.html" %}
{% load static %}
{% load common_tags %}
{% block title %}Giỏ hàng{%endblock %}
{% block content %}


<div class="container" style="margin-top: 80px;">
    <div class="col-12">
        <h1 class="h2">Giỏ hàng của bạn</h1>
    </div>
    <div class="col-12">
        <p>Quản lý <b>sản phẩm</b> trong giỏ hàng của bạn</p>
    </div>
    <hr/>
</div>
<div class="container mt-4">
    <div class="row g-3">
        {% if basket|length == 0 %}
        <div class="col-12">Giỏ hàng của bạn đang trống <a href="{% url 'store:store_home' %}">Trang chủ</a></div>
        {% else %}

        <div class="col-md-5 col-lg-4 order-md-last p-0 order-3">
            <div class="d-grid gap-2" style="margin-left: 16px">
                <span class="text-danger fw-bold"
                      id="total">Tổng tiền sản phẩm: {{basket.get_subtotal_price|currency}}</span>
                <a role="button" href="{% url 'checkout:deliverychoices' %}" class="btn btn-success fw-bold my-2"
                   type="button">Thanh toán</a>
                <a class="btn btn-light" type="button" href="/">Tiếp tục mua sắm</a>
            </div>
        </div>
        <div class="col-md-7 col-lg-8 p-0">
            {% for item in basket %}
            {% with product=item.product %}
            <div class="card mb-3 border-0 product-item" data-index="{{product.id}}">
                <div class="row g-0 py-2">
                    <div class="col-md-2 d-none d-md-block">
                        {% for image in product.product_image.all %}
                        {% if image.is_feature%}
                        <img class="img-fluid p-2" alt="Responsive image" src="{{ image.image.url }}"
                             alt="{{ image.image.alt_text }}">
                        {% endif %}
                        {% endfor %}
                    </div>
                    <div class="col-md-10 ps-md-3">
                        <div class="card-body p-1">
                            <a class="text-decoration-none" href="{{item.product.get_absolute_url}}">
                                <div class="card-text">{{product.title}}</div>
                            </a>
                            <div class="card-text my-2">Giá sản phẩm:
                                <span class="text-danger">{{product.regular_price|currency}}</span>
                            </div>
                            <label>Số lượng:</label>
                            <select id="select{{product.id}}" style="width:50px;height:31px;">
                                <option value="" selected disabled hidden>{{item.qty}}</option>
                                <option value="">1</option>
                                <option value="">2</option>
                                <option value="">3</option>
                                <option value="">4</option>
                            </select>
                            <a type="button" id="update-button" data-index="{{product.id}}"
                               class="update-button text-decoration-none small ps-3">Cập nhật</a>
                            <a type="button" id="delete-button" data-index="{{product.id}}"
                               class="delete-button text-decoration-none small" style="margin-left: 20px">Xoá</a>
                        </div>
                    </div>
                </div>
            </div>
            {% endwith %}
            {% endfor %}
        </div>
        {% endif %}
    </div>
</div>

<script>
    // Delete Item
    $(document).on("click", ".delete-button", function (e) {
        e.preventDefault();
        var prodid = $(this).data("index");
        $.ajax({
            type: "POST",
            url: '{% url "basket:basket_delete" %}',
            data: {
                productid: $(this).data("index"),
                csrfmiddlewaretoken: "{{csrf_token}}",
                action: "post",
            },
            success: function (json) {
                $('.product-item[data-index="' + prodid + '"]').remove();

                if (json.qty === 0) {
                    total = 0
                    subtotal = 0
                } else {
                    total = parseFloat(json.subtotal).toFixed(2);
                }

                document.getElementById("total").innerHTML = 'Tổng tiền sản phẩm: ' + format_currency(Number(total));
            },
            error: function (xhr, errmsg, err) {
            },
        });
    });

    // Update Item
    $(document).on("click", ".update-button", function (e) {
        e.preventDefault();
        var prodid = $(this).data("index");
        $.ajax({
            type: "POST",
            url: '{% url "basket:basket_update" %}',
            data: {
                productid: $(this).data("index"),
                productqty: $("#select" + prodid + " option:selected").text(),
                csrfmiddlewaretoken: "{{csrf_token}}",
                action: "post",
            },
            success: function (json) {
                document.getElementById("total").innerHTML = 'Tổng tiền sản phẩm: ' + format_currency(Number(json.subtotal));
            },
            error: function (xhr, errmsg, err) {
            },
        });
    });
</script>

{% endblock %}